<?php
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/agenda.php';
startSecureSession();
if (!isAuthenticated()) { header('Location: ' . appPath('/access/login.php')); exit; }

$cfg = appConfig();
$pdo = new PDO("mysql:host={$cfg['db_host']};dbname={$cfg['db_name']};charset={$cfg['db_charset']}", $cfg['db_user'], $cfg['db_pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
ensureAgendaTables($pdo);
$profileStmt = $pdo->prepare('SELECT id FROM profissionais WHERE user_id = :user_id LIMIT 1');
$profileStmt->execute([':user_id' => (int) currentUserId()]);
$professionalId = (int) $profileStmt->fetchColumn();
if (!$professionalId) { header('Location: ' . appPath('/secure/save_profile.php')); exit; }

$csrf = ensureCsrfToken();
$message = '';
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!verifyCsrfTokenOrFail($_POST['csrf_token'] ?? null)) {
        $error = 'Não foi possível salvar. Atualize a página e tente novamente.';
    } else {
        $hours = [];
        for ($day = 1; $day <= 7; $day++) {
            $start = trim((string) ($_POST['start_' . $day] ?? '07:00'));
            $end = trim((string) ($_POST['end_' . $day] ?? '18:00'));
            $hours[(string) $day] = ['active' => isset($_POST['active_' . $day]), 'start' => preg_match('/^\d{2}:\d{2}$/', $start) ? $start : '07:00', 'end' => preg_match('/^\d{2}:\d{2}$/', $end) ? $end : '18:00'];
        }
        $duration = (int) ($_POST['duracao_minutos'] ?? 60);
        $interval = (int) ($_POST['intervalo_minutos'] ?? 15);
        $lead = (int) ($_POST['antecedencia_minutos'] ?? 120);
        $limit = (int) ($_POST['limite_diario'] ?? 0);
        $stmt = $pdo->prepare('UPDATE agenda_configuracoes SET agenda_ativa = :active, duracao_minutos = :duration, intervalo_minutos = :interval, antecedencia_minutos = :lead, confirmacao_manual = :manual, limite_diario = :limit, horarios_json = :hours WHERE profissional_id = :id');
        $stmt->execute([':active' => isset($_POST['agenda_ativa']) ? 1 : 0, ':duration' => max(15, min(480, $duration)), ':interval' => max(0, min(120, $interval)), ':lead' => max(0, min(10080, $lead)), ':manual' => ($_POST['confirmacao'] ?? 'auto') === 'manual' ? 1 : 0, ':limit' => max(0, min(50, $limit)), ':hours' => json_encode($hours, JSON_UNESCAPED_UNICODE), ':id' => $professionalId]);
        $message = 'Configurações da agenda salvas.';
    }
}
$agenda = agendaGetConfig($pdo, $professionalId);
$week = [1 => 'Seg', 2 => 'Ter', 3 => 'Qua', 4 => 'Qui', 5 => 'Sex', 6 => 'Sáb', 7 => 'Dom'];
function optionSelected(int $value, $current): string { return (int) $current === $value ? 'selected' : ''; }
?>
<style>.sidebar nav > a > span { display: none; }.sidebar nav > a { gap: 0 !important; }</style>
<?php
?><script>document.addEventListener('DOMContentLoaded',function(){var s=document.createElement('style');s.textContent='@media(max-width:1023px){aside.sidebar{display:flex!important;flex-direction:column!important;height:auto!important;padding:12px!important}aside.sidebar nav{display:flex!important;flex:0 0 auto!important;height:42px!important;min-height:42px!important;margin:0!important}aside.sidebar nav>a{display:flex!important;flex:1 1 0!important;align-items:center!important;justify-content:center!important;height:42px!important;padding:0!important}aside.sidebar>.mt-auto{display:block!important;margin:12px 0 0!important;padding:0!important;border:0!important}aside.sidebar>.mt-auto a:last-child{display:none!important}}';document.head.appendChild(s)});</script>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Configurar agendamento</title><script src="https://cdn.tailwindcss.com"></script><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>body{font-family:Inter,sans-serif;background:#f6f8fc}.sidebar{background:linear-gradient(160deg,#082d59,#123e70)}@media(min-width:1024px){.sidebar{position:sticky;top:0;height:100vh;align-self:start}}@media(max-width:1023px){.sidebar{display:flex!important;position:sticky;top:0;z-index:40;min-height:0;padding:.6rem .5rem}.sidebar>div:first-child,.sidebar>.mt-auto{display:none}.sidebar nav{display:flex;flex:1;gap:.2rem;margin:0}.sidebar nav p{display:none}.sidebar nav>a{flex:1;min-width:0;overflow:hidden;padding:.68rem .2rem;text-align:center;font-size:0;white-space:nowrap}.sidebar nav>a:before{font-size:.72rem;font-weight:700}.sidebar nav>a:nth-of-type(1):before{content:"Agenda"}.sidebar nav>a:nth-of-type(2):before{content:"Loja"}.sidebar nav>a:nth-of-type(3):before{content:"Conta"}.sidebar nav>*+*{margin-top:0!important}}.card{border:1px solid #e3eaf3;background:#fff;border-radius:14px}.choice:has(input:checked){border-color:#2563eb;background:#eff6ff}.toggle:checked+span{background:#2563eb}.toggle:checked+span:after{transform:translateX(1.25rem)}input[type=time]{min-width:70px}</style></head>
<body class="min-h-screen text-slate-900"><div class="grid min-h-screen lg:grid-cols-[300px_1fr]"><aside class="sidebar hidden lg:flex flex-col p-6 text-white"><div class="flex items-center gap-3 border-b border-white/10 px-2 pb-6 font-extrabold text-base"><img src="../img/logomenor.png" class="h-8 w-8 object-contain" alt="">Clube dos Parceiros</div><nav class="mt-7 space-y-1"><p class="mb-3 px-2 text-[10px] font-bold tracking-wide text-blue-200">CONFIGURAÇÕES</p><a href="<?php echo htmlspecialchars(appPath('/access/configurar_agenda.php'), ENT_QUOTES, 'UTF-8'); ?>" class="flex items-center gap-3 rounded-lg bg-blue-600 px-3 py-3 text-sm font-bold"><span>◫</span>Agendamentos</a><a href="<?php echo htmlspecialchars(appPath('/access/mini_marketplace.php'), ENT_QUOTES, 'UTF-8'); ?>" class="flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-semibold text-blue-100 transition hover:bg-white/10 hover:text-white"><span>⊞</span>Mini marketplace</a><a href="<?php echo htmlspecialchars(appPath('/secure/conta.php'), ENT_QUOTES, 'UTF-8'); ?>" class="flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-semibold text-blue-100 transition hover:bg-white/10 hover:text-white"><span>◯</span>Conta</a></nav><div class="mt-auto space-y-3 border-t border-white/10 pt-5"><a href="<?php echo htmlspecialchars(appPath('/access/perfil.php'), ENT_QUOTES, 'UTF-8'); ?>" class="flex items-center justify-center gap-2 rounded-lg border border-white/20 px-3 py-2.5 text-sm font-bold text-white transition hover:bg-white/10">◉ Meu perfil</a><a href="<?php echo htmlspecialchars(appPath('/access/painel.php'), ENT_QUOTES, 'UTF-8'); ?>" class="flex items-center justify-center gap-2 rounded-lg bg-white px-3 py-2.5 text-sm font-bold text-[#123e70] transition hover:bg-blue-50">← Voltar ao painel</a><a href="<?php echo htmlspecialchars(appPath('/access/painel.php'), ENT_QUOTES, 'UTF-8'); ?>" class="block px-2 pt-2 text-sm font-semibold text-blue-100 transition hover:text-white">Precisa de ajuda?<small class="mt-0.5 block text-xs font-normal text-blue-200">Fale com nosso suporte</small></a></div></aside>
<main class="mx-auto w-full max-w-6xl px-4 py-8 sm:px-8 lg:px-12"><div class="mb-6 flex items-start justify-between gap-3"><div><h1 class="text-2xl font-extrabold sm:text-3xl">Configurar agendamento</h1><p class="mt-1 text-sm text-slate-500">Defina como seus clientes podem agendar seus serviços.</p></div><a href="<?php echo htmlspecialchars(appPath('/access/painel.php'), ENT_QUOTES, 'UTF-8'); ?>" class="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold hover:bg-white">Voltar ao painel</a></div>
<?php if ($message): ?><div class="mb-4 rounded-xl bg-green-50 px-4 py-3 text-sm font-semibold text-green-700"><?php echo htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?></div><?php endif; ?><?php if ($error): ?><div class="mb-4 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700"><?php echo htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></div><?php endif; ?>
<form method="post" class="space-y-3"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrf, ENT_QUOTES, 'UTF-8'); ?>">
<section class="card flex flex-col gap-5 p-5 sm:flex-row sm:items-center"><div class="flex-1"><h2 class="font-bold">1. Ativar agenda</h2><p class="mt-1 text-sm text-slate-500">Permita que clientes agendem serviços pela sua agenda online.</p></div><label class="flex cursor-pointer items-center gap-3"><input class="toggle sr-only" type="checkbox" name="agenda_ativa" <?php echo (int) $agenda['agenda_ativa'] === 1 ? 'checked' : ''; ?>><span class="relative h-6 w-11 rounded-full bg-slate-300 after:absolute after:left-1 after:top-1 after:h-4 after:w-4 after:rounded-full after:bg-white after:transition"></span><span class="text-sm font-semibold text-slate-700">Agenda ativada</span></label></section>
<section class="card p-5"><h2 class="font-bold">2. Duração média do atendimento</h2><p class="mt-1 text-sm text-slate-500">Esta duração será usada para criar os horários disponíveis.</p><div class="mt-4 flex flex-wrap gap-2"><?php foreach ([30 => '30 min', 60 => '1 hora', 90 => '1h 30 min', 120 => '2 horas'] as $value => $label): ?><label class="choice cursor-pointer rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold"><input class="sr-only" name="duracao_minutos" type="radio" value="<?php echo $value; ?>" <?php echo (int) $agenda['duracao_minutos'] === $value ? 'checked' : ''; ?>><?php echo $label; ?></label><?php endforeach; ?></div></section>
<section class="card p-5"><h2 class="font-bold">3. Dias e horários de atendimento</h2><p class="mt-1 text-sm text-slate-500">Marque os dias em que você atende e ajuste o horário de cada um.</p><div class="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><?php foreach ($week as $day => $label): $h = $agenda['hours'][(string) $day]; ?><label class="flex items-center gap-3 rounded-lg border border-slate-200 p-3"><input type="checkbox" name="active_<?php echo $day; ?>" <?php echo !empty($h['active']) ? 'checked' : ''; ?>><span class="w-8 text-sm font-bold"><?php echo $label; ?></span><input type="time" name="start_<?php echo $day; ?>" value="<?php echo htmlspecialchars($h['start'], ENT_QUOTES, 'UTF-8'); ?>" class="rounded border border-slate-200 px-1 py-1 text-xs"><span class="text-slate-400">–</span><input type="time" name="end_<?php echo $day; ?>" value="<?php echo htmlspecialchars($h['end'], ENT_QUOTES, 'UTF-8'); ?>" class="rounded border border-slate-200 px-1 py-1 text-xs"></label><?php endforeach; ?></div></section>
<section class="card p-5"><h2 class="font-bold">4. Intervalo entre serviços</h2><p class="mt-1 text-sm text-slate-500">Tempo livre entre um atendimento e outro.</p><div class="mt-4 flex flex-wrap gap-2"><?php foreach ([0 => '0 min', 15 => '15 min', 30 => '30 min', 45 => '45 min', 60 => '60 min'] as $value => $label): ?><label class="choice cursor-pointer rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold"><input class="sr-only" name="intervalo_minutos" type="radio" value="<?php echo $value; ?>" <?php echo (int) $agenda['intervalo_minutos'] === $value ? 'checked' : ''; ?>><?php echo $label; ?></label><?php endforeach; ?></div></section>
<section class="card p-5"><h2 class="font-bold">5. Antecedência mínima</h2><p class="mt-1 text-sm text-slate-500">Prazo que o cliente deve respeitar antes de agendar.</p><div class="mt-4 flex flex-wrap gap-2"><?php foreach ([30 => '30 min', 60 => '1 hora', 120 => '2 horas', 1440 => '1 dia', 2880 => '2 dias'] as $value => $label): ?><label class="choice cursor-pointer rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold"><input class="sr-only" name="antecedencia_minutos" type="radio" value="<?php echo $value; ?>" <?php echo (int) $agenda['antecedencia_minutos'] === $value ? 'checked' : ''; ?>><?php echo $label; ?></label><?php endforeach; ?></div></section>
<section class="card p-5"><h2 class="font-bold">6. Confirmação de agendamentos</h2><div class="mt-4 grid gap-3 md:grid-cols-2"><label class="choice cursor-pointer rounded-xl border border-slate-200 p-4"><input class="sr-only" name="confirmacao" type="radio" value="auto" <?php echo empty($agenda['confirmacao_manual']) ? 'checked' : ''; ?>><span class="font-bold">Confirmação automática</span><span class="mt-1 block text-sm text-slate-500">O agendamento é confirmado assim que o cliente finalizar.</span></label><label class="choice cursor-pointer rounded-xl border border-slate-200 p-4"><input class="sr-only" name="confirmacao" type="radio" value="manual" <?php echo !empty($agenda['confirmacao_manual']) ? 'checked' : ''; ?>><span class="font-bold">Confirmação manual</span><span class="mt-1 block text-sm text-slate-500">Você aprova o agendamento antes de confirmar para o cliente.</span></label></div></section>
<section class="card flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold">Opções avançadas</h2><label class="mt-2 block text-sm text-slate-600">Máximo de atendimentos por dia <input type="number" min="0" max="50" name="limite_diario" value="<?php echo (int) $agenda['limite_diario']; ?>" class="ml-2 w-20 rounded border border-slate-300 px-2 py-1"> <span class="text-xs text-slate-400">0 = sem limite</span></label></div><button class="rounded-xl bg-blue-700 px-6 py-3 font-bold text-white hover:bg-blue-800">Salvar configurações</button></section></form></main></div></body></html>
